/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fafaef',
        'on-primary-fixed-variant': '#2e4e35',
        'on-tertiary-container': '#a6d3a2',
        'on-error-container': '#93000a',
        'inverse-surface': '#2f312a',
        'on-error': '#ffffff',
        'on-background': '#1a1c16',
        'surface-bright': '#fafaef',
        'tertiary-fixed-dim': '#a5d2a2',
        'surface-variant': '#e3e3d8',
        'surface-container-low': '#f4f4e9',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f1f1e6',
        'border-muted': '#E5E3D7',
        'secondary-container': '#d7e5bb',
        surface: '#fafaef',
        'text-rich': '#344E41',
        'surface-container-high': '#e9e9de',
        'on-surface-variant': '#424842',
        'tertiary-fixed': '#c1eebc',
        secondary: '#566342',
        'on-surface': '#1a1c16',
        'on-secondary': '#ffffff',
        tertiary: '#1d4420',
        'surface-dim': '#dadbd0',
        primary: '#23422a',
        'primary-fixed': '#c7ecca',
        'primary-container': '#3a5a40',
        'inverse-primary': '#abd0af',
        'surface-container': '#eeeee4',
        'on-secondary-fixed': '#141f05',
        'on-primary-fixed': '#02210c',
        'primary-fixed-dim': '#abd0af',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#dae8be',
        'surface-cream': '#F3F3E9',
        'outline-variant': '#c2c8bf',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'status-water': '#4A90E2',
        'on-secondary-container': '#5a6745',
        'tertiary-container': '#355c36',
        'surface-tint': '#45664b',
        outline: '#727971',
        'on-tertiary-fixed-variant': '#284f2a',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#002106',
        'secondary-fixed-dim': '#becca3',
        'surface-container-highest': '#e3e3d8',
        'on-secondary-fixed-variant': '#3f4b2c',
        'on-primary-container': '#acd0af',
        /** Dashboard canvas (mockup) */
        canvas: '#F2F1E0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        /** Landing / wide layouts */
        gutter: '24px',
        /** Analytics mock: tighter horizontal rhythm */
        'content-gutter': '16px',
        'container-max': '1280px',
        margin: '16px',
        /** Dashboard main padding (md+) */
        pageMargin: '32px',
        'md-margin': '24px',
        'lg-margin': '32px',
      },
      boxShadow: {
        sage: '0 4px 24px rgba(58, 90, 64, 0.08)',
        'sage-lg': '0 12px 32px rgba(58, 90, 64, 0.12)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      padding: {
        safe: 'env(safe-area-inset-bottom, 0px)',
      },
      fontFamily: {
        'label-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-xl': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'data-display': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'data-display': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
